services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached

    command: sleep infinity
    network_mode: service:ia
  ia:
    build:
      context: .
      dockerfile: Dockerfile.ia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - '8090:8080'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - models_data:/models
      - ./docker-ia-entrypoint.sh:/usr/local/bin/docker-ia-entrypoint.sh:ro   #En Volumen para hacer cambios sin tener que cosrecostruirlo

volumes:
  models_data:
    external: true
