name: "Mi Configuración repo"
version: "1"

models:
  - name: Qwen3-Coder-30B-A3B-Instruct
    provider: openai
    model: Qwen3-Coder-30B-A3B-Instruct
    apiBase: http://ia:8080/
    completionType: completion
    capabilities:
      - tool_use
    streaming: true
    roles:
      - chat
      - rerank
      - edit
      - apply

context:
  - provider: file
  - provider: code
  - provider: diff
  - provider: currentFile
  - provider: terminal
  - provider: open
  - provider: clipboard
  - provider: tree
  - provider: problems
  - provider: debugger
    params:
      stackDepth: 3
  - provider: repo-map
    params:
      includeSignatures: false # default true
  # - provider: http
  #   params:
  #     url: "https://api.example.com/v1/users"
  #     headers:
  #       - Authorization: "Bearer <token>"
  - provider: docs
  - provider: folder
  - provider: codebase
