name: "Mi Configuración repo"
version: "1"

models:
  - name: Qwen3-Coder-30B-A3B-Instruct
    provider: openai
    model: Qwen3-Coder-30B-A3B-Instruct
    apiBase: http://ia:8080/v1
    # completionType: completion
    chatOptions:
      baseSystemMessage: "You are a helpful coding agent."
      baseAgentSystemMessage: "You are a systematic coding agent. Break down problems methodically."
      basePlanSystemMessage: "You are a planning agent. Create clear, actionable steps."
    maxStopWords: 3000
    capabilities:
      - tool_use
    roles:
      - apply
      - chat
      - edit

context:
  - provider: file
  - provider: code
  - provider: diff
  - provider: currentFile
  - provider: terminal
  - provider: open
  - provider: clipboard
  - provider: tree
  - provider: problems
  - provider: debugger
    params:
      stackDepth: 3
  - provider: repo-map
    params:
      includeSignatures: false # default true
  # - provider: http
  #   params:
  #     url: "https://api.example.com/v1/users"
  #     headers:
  #       - Authorization: "Bearer <token>"
  - provider: docs
  - provider: folder
  - provider: codebase

