name: "Mi Configuración repo"
version: "1"

models:
  - name: Qwen3-Coder-30B-A3B-Instruct
    provider: openai
    model: Qwen3-Coder-30B-A3B-Instruct
    apiBase: http://proxy:8080/v1
    # completionType: completion
    chatOptions:
      baseSystemMessage: "You are a helpful coding agent."
      baseAgentSystemMessage: ""
      basePlanSystemMessage: "You are a planning agent. Create clear, actionable steps."
    capabilities:
      - tool_use
    roles:
      - apply
      - chat
      - edit

  - name: openrouter:openai/gpt-oss-20b:free
    provider: openai
    model: openai/gpt-oss-20b:free
    apiBase: http://proxy:8080/v1
    apiKey: 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
    stream: false
    chatOptions:
      baseSystemMessage: "You are a helpful coding agent."
      baseAgentSystemMessage: "eres un agente"
      basePlanSystemMessage: "You are a planning agent. Create clear, actionable steps."
    capabilities:
      - tool_use
    roles:
      - apply
      - chat
      - edit

context:
  - provider: file
  - provider: code
  - provider: diff
  - provider: currentFile
  - provider: terminal
  - provider: open
  - provider: clipboard
  - provider: tree
  - provider: problems
  - provider: debugger
    params:
      stackDepth: 3
  - provider: repo-map
    params:
      includeSignatures: false # default true
  # - provider: http
  #   params:
  #     url: "https://api.example.com/v1/users"
  #     headers:
  #       - Authorization: "Bearer <token>"
  - provider: docs
  - provider: folder
  - provider: codebase

